FitHub/config/routes.rb
Rails.application.routes.draw do
  get 'create/destroy'

  resources :likes

  resources :friendships

  root 'pages#index'
  get 'users/profile'
  get 'users/home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'users/show', to: 'users#profile'
  delete 'sign_out', to: 'sessions#destroy'
  resources :exercises
  resources :users
  resources :workouts
  resources :users_workouts
  resources :users_gyms
  resources :workouts_exercises
  resources :weekdays
  resources :weekdays_workouts
  get 'my_workouts', to: 'workouts#my_workouts'
  get 'followed', to: 'workouts#followed'
  post 'results', to: 'gyms#results'
  resources :gyms

end

FitHub/app/models/exercise.rb
class Exercise < ActiveRecord::Base
  # has_many :workout_exercises
  # has_many :workouts, through: :workout_exercises
  has_many :workouts_exercises
  has_many :workouts, through: :workouts_exercises
  has_many :sets_and_reps
end

FitHub/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :user
belongs_to :friend, :class_name => "User"
end

FitHub/app/models/gym.rb
class Gym < ActiveRecord::Base
  validates_uniqueness_of :address
  has_many :users_gyms
  has_many :users, through: :users_gyms

  def joined_gyms(user)
    UsersGym.where(:user_id => user.id, :gym_id => self.id).first
  end
end

FitHub/app/models/gyms_user.rb
class GymsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/like.rb
class Like < ActiveRecord::Base
 belongs_to :user
 belongs_to :workout
end

FitHub/app/models/sets_and_rep.rb
class SetsAndRep < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_gyms
  has_many :gyms, through: :users_gyms
  has_many :users_workouts
  has_many :workouts, through: :users_workouts, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # has_many :likes
  # has_many :workouts, :through => :likes
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      # image: auth['info']['image']
    )
  end

  def is_friend?(friend_id)
    friendships.collect {|friendship| friendship.friend_id}.include?(friend_id)
  end
end

FitHub/app/models/users_gym.rb
class UsersGym < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/users_workout.rb
class UsersWorkout < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout

   def self.notexist?(user, workout)
     !UsersWorkout.exists?(:user_id => user.id, :workout_id => workout.id)
   end
end

FitHub/app/models/weekday.rb
class Weekday < ActiveRecord::Base
  has_many :weekdays_workouts
  has_many :workouts, through: :weekdays_workouts
end

FitHub/app/models/weekdays_workout.rb
class WeekdaysWorkout < ActiveRecord::Base
  belongs_to :weekday
  belongs_to :workout
end

FitHub/app/models/workout.rb
class Workout < ActiveRecord::Base
 has_many :workouts_exercises
 has_many :exercises, through: :workouts_exercises
 has_many :users_workouts
 has_many :users, through: :users_workouts
 has_many :likes
 has_many :sets_and_reps
 has_many :weekdays_workouts
 has_many :weekdays, through: :weekdays_workouts
 attr_accessor :sets
 attr_accessor :reps
 attr_accessor :ex_num
 attr_accessor :days


 def followed_workouts(user)
   UsersWorkout.where(:user_id => user.id, :workout_id => self.id).first
 end

 def self.search(search)
   amt_for_category_search = where('category LIKE ?', "%#{search}%").count
   amt_for_name_search = where('name LIKE ?', "%#{search}%").count
   amt_for_creator_search = where('creator like ?', "%#{search}%").count

   if amt_for_category_search > amt_for_name_search && amt_for_category_search > amt_for_creator_search
     where('category LIKE ?', "%#{search}%")
   elsif amt_for_name_search > amt_for_creator_search && amt_for_name_search > amt_for_category_search
     where('name LIKE ?', "%#{search}%")
   else amt_for_creator_search > amt_for_name_search && amt_for_creator_search > amt_for_category_search
     where('creator like ?', "%#{search}%")
   end
 end

end

FitHub/app/models/workouts_exercise.rb
class WorkoutsExercise < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  # GET /gyms
  # GET /gyms.json
  def index
    @gyms = Gym.all
    @users_gym = UsersGym.new
  end

  def results
    search = params[:keyword]
    @city = params[:city]
    api_key = "AIzaSyBNlEoTVzUn-VAoNUeUOSxWt5n40z8DaME"
    client = GooglePlaces::Client.new(api_key)
    @gyms_results = client.spots_by_query("#{search} near #{@city}, NY", :types => "gym", :radius => 8000)
  end

  # GET /gyms/1
  # GET /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms
  # POST /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to gyms_path, notice: 'Added Gym to FitHub Database!' }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1
  # PATCH/PUT /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to @gym, notice: 'Gym was successfully updated.' }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1
  # DELETE /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: 'Gym was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym
      @gym = Gym.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gym_params
      params.require(:gym).permit(:name, :address, :latitude, :longitude)
    end
end

FitHub/app/helpers/exercises_helper.rb
module ExercisesHelper
end

FitHub/app/helpers/gyms_helper.rb
module GymsHelper
end

FitHub/app/helpers/gyms_users_helper.rb
module GymsUsersHelper
end

FitHub/app/helpers/likes_helper.rb
module LikesHelper
end

FitHub/app/helpers/pages_helper.rb
module PagesHelper
end

FitHub/app/helpers/sessions_helper.rb
module SessionsHelper
end

FitHub/app/helpers/users_helper.rb
module UsersHelper

  def display_status(alert_type, flash_type)
    <<-eos
    <div class="container-fluid" id="medium_size">
      <div class="alert alert-#{alert_type}" role="alert">
        <p align="center">
          #{send(flash_type)}
        </p>
      </div>
    </div>
    eos
  end
end

FitHub/app/helpers/weekdays_helper.rb
module WeekdaysHelper
end

FitHub/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

FitHub/app/views/gyms/_form.html.erb
<%= form_for(@gym) do |f| %>
  <% if @gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% @gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FitHub/app/views/gyms/edit.html.erb
<h1>Editing Gym</h1>

<%= render 'form' %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

FitHub/app/views/gyms/index.html.erb
<div align="center" class="form-group">
  <%= form_tag(results_path, method: "post") do %>
  <strong>Gym Name<br></strong>
  <%= text_field_tag :keyword %><br><br>
  <strong>City<br></strong>
  <%= text_field_tag :city %><br><br>
  <%= submit_tag "Search For Gyms", class: "btn btn-primary" %><br>
  <% end %>
</div><br>

<div class="container-fluid">
  <div align="center">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Address</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @gyms.each do |gym| %>
                <tr>
                  <td>
                    <%= link_to(gym) do %>
                    <%= gym.name %>
                    <% end %>
                  </td>
                  <td><%= gym.address %></td>
                  <td>
                    <% if current_user.gyms.include?(gym) %>
                    <strong>Added!</strong>
                    <% else %>
                    <%= form_for @users_gym do |f| %>
                    <%= f.hidden_field :gym_id, :value => gym.id %>
                    <%= f.submit "Add To My Gyms", class: "btn btn-primary btn-xs" %>
                    <% end %>
                  </td>
                </tr>
                <% end %>
              </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-3"></div>
    </div>

  </div>

</div>

FitHub/app/views/gyms/new.html.erb
<h1>New Gym</h1>

<%= render 'form' %>

<%= link_to 'Back', gyms_path %>

FitHub/app/views/gyms/results.html.erb
<% @gyms_results.each do |element| %>
  <% gym_address = element["formatted_address"] %>
  <% if gym_address.include?(@city.capitalize) %>
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="container-fluid">
        <div class="well well-sm">
          <div align="center">
            <h4><%= element["name"] %></h4>
            <h4><%= gym_address %></h4>
            <h4><%= link_to "Map", "http://maps.google.com/?q=#{gym_address}", class: "btn btn-primary btn-xs" %></h4>
            <%= form_for(Gym.new, method: :post) do |f| %>
              <%= f.hidden_field :name, :value => element.name %>
              <%= f.hidden_field :address, :value => gym_address %>
              <%= f.hidden_field :latitude, :value => element.lat %>
              <%= f.hidden_field :longitude, :value => element.lng %>
              <%= f.submit "Add Gym To FitHub Database", :class => "btn btn-primary" %><br>
            <% end %>
          </div>

        </div>
      </div>
    </div>
    <div class="col-md-3"></div>

  </div>

  <% end %>
<% end %>

FitHub/app/views/gyms/show.html.erb
<% if notice %>
<div class="container-fluid" id="medium_size">
  <div class="alert alert-success" role="alert">
    <p align="center">
      <%= notice %>
    </p>
  </div>
</div>
<% end %>

  <div align="center">
    <h3><%= @gym.name %></h3>
    <h3><%= @gym.address %></h3>
  </div>
  <div class="container-fluid">
    <div align="center">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4>All The People In This Gym</h4>
            </div>
              <table class="table table-hover">
                <thead>
                  <tr>
                    <center>
                      <th>Name</th>
                    </center>
                  </tr>
                  <% @gym.users.each do |user| %>
                  <tr>
                    <td>
                        <%= link_to(user) do %>
                          <%= user.name %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                </thead>
              </table>
          </div>
        </div>
      </div>
    </div>
  </div>


<center>
  <h2><%= link_to 'Back', gyms_path %></h2>
</center>