FitHub/config/routes.rb
Rails.application.routes.draw do
  get 'create/destroy'

  resources :likes

  resources :friendships

  root 'pages#index'
  get 'users/profile'
  get 'users/home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'users/show', to: 'users#profile'
  delete 'sign_out', to: 'sessions#destroy'
  resources :exercises
  resources :users
  resources :workouts
  resources :users_workouts
  resources :users_gyms
  resources :workouts_exercises
  resources :weekdays
  resources :weekdays_workouts
  get 'my_workouts', to: 'workouts#my_workouts'
  get 'followed', to: 'workouts#followed'
  post 'results', to: 'gyms#results'
  resources :gyms

end

FitHub/app/models/workout.rb
class Workout < ActiveRecord::Base
 has_many :workouts_exercises
 has_many :exercises, through: :workouts_exercises
 has_many :users_workouts
 has_many :users, through: :users_workouts
 has_many :likes
 has_many :sets_and_reps
 has_many :weekdays_workouts
 has_many :weekdays, through: :weekdays_workouts
 attr_accessor :sets
 attr_accessor :reps
 attr_accessor :ex_num
 attr_accessor :days


 def followed_workouts(user)
   UsersWorkout.where(:user_id => user.id, :workout_id => self.id).first
 end

 def self.search(search)
   amt_for_category_search = where('category LIKE ?', "%#{search}%").count
   amt_for_name_search = where('name LIKE ?', "%#{search}%").count
   amt_for_creator_search = where('creator like ?', "%#{search}%").count

   if amt_for_category_search > amt_for_name_search && amt_for_category_search > amt_for_creator_search
     where('category LIKE ?', "%#{search}%")
   elsif amt_for_name_search > amt_for_creator_search && amt_for_name_search > amt_for_category_search
     where('name LIKE ?', "%#{search}%")
   else amt_for_creator_search > amt_for_name_search && amt_for_creator_search > amt_for_category_search
     where('creator like ?', "%#{search}%")
   end
 end

end

FitHub/app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user, :current_user
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json

  def authenticate_user
    if current_user.nil?
      redirect_to root_url
    end
  end

  def index
    if params[:search]
      @workouts = Workout.search(params[:search])
    else
      @workouts = Workout.all
    end
  end

  def my_workouts
    @my_workouts = current_user.workouts
  end

  def followed
    @followed_workout_ids = []
    @followed_workouts = []
    UsersWorkout.where(:user_id => current_user.id).each do |x|
      @followed_workout_ids << x.workout_id
    end
    @followed_workout_ids.each do |id|
      if Workout.find(id).creator != current_user.name
        @followed_workouts << Workout.find(id)
      end
    end

  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @like = Like.new
    @users_workout = UsersWorkout.new
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create

    @workout = Workout.new(workout_params)
    respond_to do |format|

      if @workout.save
        if params[:days]
          params[:days].each do |day|
            WeekdaysWorkout.create(:weekday_id => Weekday.find_by_name(day).id, :workout_id => @workout.id)
          end
        end
        if params[:details]
        #wire up the sets and reps for this particular workout
          params[:details].each do |data|
            SetsAndRep.create(:workout_id => @workout.id, :exercise_id => data[:ex_num].to_i, :sets => data[:sets].to_i, :reps => data[:reps].to_i)
          end
        end
        # create the realationship between the workout and the user
        UsersWorkout.create(:user_id => current_user.id, :workout_id => @workout.id)


        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    if params[:details]
    #update up the sets and reps for this particular workout
    SetsAndRep.where(:workout_id => @workout.id).delete_all
      params[:details].each do |data|
        SetsAndRep.create(:workout_id => @workout.id, :exercise_id => data[:ex_num].to_i, :sets => data[:sets].to_i, :reps => data[:reps].to_i)
      end
    end
    respond_to do |format|
      if @workout.update(workout_params) && @workout.user_id == current_user.id
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { redirect_to @workout, notice: 'You are not allowed to edit this workout!' }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    UsersWorkout.where(:workout_id => @workout.id).destroy_all
    SetsAndRep.where(:workout_id => @workout.id).destroy_all
    WorkoutsExercise.where(:workout_id => @workout.id).destroy_all
    Like.where(:workout_id => @workout.id).destroy_all

    respond_to do |format|
      format.html { redirect_to my_workouts_url, notice: 'Workout was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:name, :likes, :creator, :category, :user_id, :description, :challenges, :exercise_ids => [])
    end

end

FitHub/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

FitHub/app/views/workouts/edit.html.erb
<center>
  <h1>Editing Workout</h1>
</center>

<%= render 'form' %>

FitHub/app/views/workouts/followed.html.erb
<% if notice %>
<div class="container-fluid" id="medium_size">
  <div class="alert alert-success" role="alert">
    <p align="center">
      <%= notice %>
    </p>
  </div>
</div>
<% end %>

<% if @followed_workouts.count == 1 %>
<center>
  <h1>You have followed
    <%= @followed_workouts.count %>
    workout so far!</h1>
</center><br>
<% else %>
<center>
  <h1>You have followed
    <%= @followed_workouts.count %>
    workouts so far!</h1>
</center><br>
<% end %>

<% @followed_workouts.each do |workout| %>

<div class="row">
  <div align="center">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3>Created By:
          </h3>
          <h4><%= workout.creator %></h4>
          <h3>Workout:
          </h3>
          <h4><%= workout.name %></h4>
          <h3>Category:
          </h3>
          <h4><%= workout.category %></h4>
          <h3>Description of Workout:
          </h3>
          <h4><%= workout.description %></h4>
          <h3>Challenges:
          </h3>
          <h4><%= workout.challenges %></h4>
          <h4><%= link_to 'Show', workout %></h4>

          <% if workout.followed_workouts(current_user) %>
          <%= form_for workout.followed_workouts(current_user), method: :delete do |f| %>
          <h4><%= f.submit "Unfollow This Workout", :class => "btn btn-primary"%></h4>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>
<% end %>

FitHub/app/views/workouts/index.html.erb
<% if params[:search] %>
<% if @workouts.count == 1 %>
<center>
  <h2>There is
    <%= @workouts.count %>
    workout that matches your search!</h2>
</center>
<% else %>
<center>
  <h2>There are
    <%= @workouts.count %>
    workouts that matches your search!</h2>
</center>
<% end %>
<div class="container-fluid">
  <div align="center">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="panel panel-primary">
          <div class="panel-heading">Workouts</div>
          <table class="table">

            <tr>
              <th>Title</th>
              <th>Category</th>
              <th>Creator</th>
              <th></th>
            </tr>
            <% @workouts.each do |workout| %>
            <tr>
              <td><%= link_to workout.name, workout, class: "btn btn-primary btn-xs" %></td>
              <td><%= workout.category %></td>
              <td><%= workout.creator %></td>
              <td>
                <i class="fa fa-heartbeat fa-lg">
                  <%= workout.likes.count %></i>
              </td>
            </tr>
            <% end %>

          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<center>
  <h3><%= link_to "Back To All Workouts", workouts_path %></h3>
</center>
<% else %>
<center>
  <h2>All Workouts Created On FitHub</h2>
</center>
<div class="panel panel-default" style="min-height:700px;">
<% if @workouts.count == 1 %>
<center>
  <h2>People like you have created
    <%= @workouts.count %>
    workout on FitHub!</h2>
</center>
<% else %>
<center>
  <h2>People like you have created
    <%= @workouts.count %>
    workouts on FitHub!</h2>
</center>
<% end %>

<center>
  <form class="form-inline">
    <%= form_tag workouts_path, :method => 'get' do %>
    <p>
      <i>Search by Category, Workout Name, or Creator</i><br>
      <div id="workouts-input">
        <%= text_field_tag :search, params[:search], class: "form-control" %>
        <%= submit_tag "Search", :name => nil, class:"btn btn-primary btn-md" %>
      </div>
    </p>
    <% end %>
  </form>
</center>
<div class="container-fluid">
  <div align="center">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="panel panel-primary">
          <div class="panel-heading">Workouts</div>
          <table class="table">

            <tr>
              <th>Title</th>
              <th>Category</th>
              <th>Creator</th>
              <th></th>
            </tr>
            <% @workouts.each do |workout| %>
            <tr>
              <div style="color:black"><td><%= link_to workout.name, workout, class: "btn btn-primary btn-xs" %></td></div>
              <td><%= workout.category %></td>
              <td><%= workout.creator %></td>
              <td>
                <i class="fa fa-heartbeat fa-lg">
                  <%= workout.likes.count %></i>
              </td>
            </tr>
            <% end %>

          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<% end %>

FitHub/app/views/workouts/my_workouts.html.erb
<% if notice %>
<div class="container-fluid" id="medium_size">
  <div class="alert alert-success" role="alert">
    <p align="center">
      <%= notice %>
    </p>
  </div>
</div>
<% end %>
<% @workout_count= [] %>
<% @my_workouts.each do |workout| %>
<% if workout.user_id == current_user.id %>
<% @workout_count << workout %>
<% end %>
<% @workout_count %>
<% end %>
<% if @workout_count.count == 1 %>
<center>
  <h1>You have created
    <%= @workout_count.count %>
    workout so far!</h1>
</center><br>
<% else %>
<center>
  <h1>You have created
    <%= @workout_count.count %>
    workouts so far!</h1>
</center><br>
<% end %>
<% @my_workouts.each do |workout| %>
<% if workout.user_id == current_user.id %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6" align="center">
    <div class="panel panel-default">

      <div align="center" class="panel-heading">
        <h3><%= workout.name %></h3>
      </div>
      <div align="center" class="panel-body">
        <h3>Created By: <%= workout.creator %></h3>
        <h3>Category: <%= workout.category %></h3>
        <h3>Description of Workout: <%= workout.description %></h3>
        <h3>Challenges: <%= workout.challenges %></h3><br>
        <p>
          <%= link_to 'Go to Workout', workout, class: "btn btn-primary" %>
          <%= link_to '<i class="fa fa-trash"></i> Delete'.html_safe, workout, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </p>
      </div>
      <div class="col-md-3"></div>

    </div>
    <% end %>
  </div>
</div>
<% end %>

FitHub/app/views/workouts/new.html.erb
<center>
  <h1>Let's Make A New Workout</h1>
</center>

<%= render 'form' %>

FitHub/app/views/workouts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


    <div class="row">
        <div class="col-md-3">
          <center>
            <h3>This is a Workout for </h3>
          </center>
            <% @workout.weekdays.each do |day| %>
              <div class="well well-sm">
                <center>
                  <h2><%= day.name %>s</h2>
                </center>
              </div>

            <% end %>
        </div>


        <div class="col-md-6">
          <div class="row"><br><br><br>
            <div class="well well-sm">
              <h3>Created By: <%= @workout.creator %></h3>
              <h3>Workout: <%= @workout.name %></h3>
              <h3>Category: <%= @workout.category %></h3>
              <h3>Description of Workout: <%= @workout.description %></h3>
              <h3>Challenges: <%= @workout.challenges %></h3><br>




          </div>
          <% @workout.exercises.each do |e| %>


              <div class="well well-sm">
                <h3><%= e.name %><br></h3>
                <h5>Category: <%= e.muscle_group %><br></h5>
                <h5>Muscles Worked: <%= e.specific_muscles_worked %><br></h5>
                <h5> <p>
                  How-To: <%= e.guide %><br>
                </p><br></h5>
                <div align="center"><img src="<%=e.pic_left %>" style="max-width:47.5%;height:auto"> <img src="<%= e.pic_right.gsub("1.jpg", "2.jpg") %>" style="max-width:47.5%;height:auto;"></div><br><br>
                  <h4>Sets For This Exercise: <%= SetsAndRep.where(:exercise_id => e.id, :workout_id => @workout.id)[0].sets %></h4>
                  <h4>Reps For This Exercise: <%= SetsAndRep.where(:exercise_id => e.id, :workout_id => @workout.id)[0].reps %></h4>


              </div>
            <% end %>
            <!-- If the first user for the workout is not the current user  -->
            <!-- And if the users for the workout includes current user -->



            <% if able_to_join(current_user, @workout) %>
              <%= form_for @users_workout, method: :post do |f| %>
              <%= f.hidden_field :workout_id, :value => @workout.id%>
              <%= f.hidden_field :user_id, :value => current_user.id%>
              <center>
                <%= f.submit "Join This Workout!", :class => "btn btn-primary" %>
              </center>
              <% end %>
            <% end %>
            <% if able_to_like(current_user, @workout).empty? && @workout.user_id != current_user.id %>
              <%= form_for @like, method: :post do |f| %>
              <%= f.hidden_field :workout_id, :value => @workout.id%>
              <%= f.hidden_field :user_id, :value => current_user.id%>
              <center>
                <br><%= f.submit "Like This Workout!", :class => "btn btn-primary" %>
              </center>
            <% end %>

            <% end %>

        </div>
        <div class="col-md-3"></div>

    </div>





<% if @workout.user_id == current_user.id %>
  <center>
    <h3><%= link_to 'Edit', edit_workout_path(@workout), :class => "btn btn-primary" %> | <%= link_to 'Back', my_workouts_path,:class => "btn btn-primary" %></h3>
  </center>
<% else %>
<center>
  <h3><%= link_to 'Back', my_workouts_path %></h3>
</center>
<% end %>