FitHub/config/routes.rb
Rails.application.routes.draw do
  get 'create/destroy'

  resources :likes

  resources :friendships

  root 'pages#index'
  get 'users/profile'
  get 'users/home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'users/show', to: 'users#profile'
  delete 'sign_out', to: 'sessions#destroy'
  resources :exercises
  resources :users
  resources :workouts
  resources :users_workouts
  resources :users_gyms
  resources :workouts_exercises
  resources :weekdays
  resources :weekdays_workouts
  get 'my_workouts', to: 'workouts#my_workouts'
  get 'followed', to: 'workouts#followed'
  post 'results', to: 'gyms#results'
  resources :gyms

end

FitHub/app/models/exercise.rb
class Exercise < ActiveRecord::Base
  # has_many :workout_exercises
  # has_many :workouts, through: :workout_exercises
  has_many :workouts_exercises
  has_many :workouts, through: :workouts_exercises
  has_many :sets_and_reps
end

FitHub/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :user
belongs_to :friend, :class_name => "User"
end

FitHub/app/models/gym.rb
class Gym < ActiveRecord::Base
  validates_uniqueness_of :address
  has_many :users_gyms
  has_many :users, through: :users_gyms

  def joined_gyms(user)
    UsersGym.where(:user_id => user.id, :gym_id => self.id).first
  end
end

FitHub/app/models/gyms_user.rb
class GymsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/like.rb
class Like < ActiveRecord::Base
 belongs_to :user
 belongs_to :workout
end

FitHub/app/models/sets_and_rep.rb
class SetsAndRep < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_gyms
  has_many :gyms, through: :users_gyms
  has_many :users_workouts
  has_many :workouts, through: :users_workouts, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # has_many :likes
  # has_many :workouts, :through => :likes
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      # image: auth['info']['image']
    )
  end

  def is_friend?(friend_id)
    friendships.collect {|friendship| friendship.friend_id}.include?(friend_id)
  end
end

FitHub/app/models/users_gym.rb
class UsersGym < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/users_workout.rb
class UsersWorkout < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout

   def self.notexist?(user, workout)
     !UsersWorkout.exists?(:user_id => user.id, :workout_id => workout.id)
   end
end

FitHub/app/models/weekday.rb
class Weekday < ActiveRecord::Base
  has_many :weekdays_workouts
  has_many :workouts, through: :weekdays_workouts
end

FitHub/app/models/weekdays_workout.rb
class WeekdaysWorkout < ActiveRecord::Base
  belongs_to :weekday
  belongs_to :workout
end

FitHub/app/models/workout.rb
class Workout < ActiveRecord::Base
 has_many :workouts_exercises
 has_many :exercises, through: :workouts_exercises
 has_many :users_workouts
 has_many :users, through: :users_workouts
 has_many :likes
 has_many :sets_and_reps
 has_many :weekdays_workouts
 has_many :weekdays, through: :weekdays_workouts
 attr_accessor :sets
 attr_accessor :reps
 attr_accessor :ex_num
 attr_accessor :days


 def followed_workouts(user)
   UsersWorkout.where(:user_id => user.id, :workout_id => self.id).first
 end

 def self.search(search)
   amt_for_category_search = where('category LIKE ?', "%#{search}%").count
   amt_for_name_search = where('name LIKE ?', "%#{search}%").count
   amt_for_creator_search = where('creator like ?', "%#{search}%").count

   if amt_for_category_search > amt_for_name_search && amt_for_category_search > amt_for_creator_search
     where('category LIKE ?', "%#{search}%")
   elsif amt_for_name_search > amt_for_creator_search && amt_for_name_search > amt_for_category_search
     where('name LIKE ?', "%#{search}%")
   else amt_for_creator_search > amt_for_name_search && amt_for_creator_search > amt_for_category_search
     where('creator like ?', "%#{search}%")
   end
 end

end

FitHub/app/models/workouts_exercise.rb
class WorkoutsExercise < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params[:exercise]
    end
end

FitHub/app/helpers/exercises_helper.rb
module ExercisesHelper
end

FitHub/app/helpers/gyms_helper.rb
module GymsHelper
end

FitHub/app/helpers/likes_helper.rb
module LikesHelper
end

FitHub/app/helpers/pages_helper.rb
module PagesHelper
end

FitHub/app/helpers/sessions_helper.rb
module SessionsHelper
end

FitHub/app/helpers/users_helper.rb
module UsersHelper

  def display_status(alert_type, flash_type)
    <<-eos
    <div class="container-fluid" id="medium_size">
      <div class="alert alert-#{alert_type}" role="alert">
        <p align="center">
          #{send(flash_type)}
        </p>
      </div>
    </div>
    eos
  end
end

FitHub/app/helpers/weekdays_helper.rb
module WeekdaysHelper
end

FitHub/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

FitHub/app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FitHub/app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

FitHub/app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercises</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <div class="well">
    <h1>Arm Exercises</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Arms'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div>
    <div class="well">
    <h1>Leg Exercises</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Legs'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div>
    <div class="well">
    <h1>Back Exercises</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Back'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div>
    <div class="well">
    <h1>Shoulder Exercise</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Shoulders'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div>
    <div="well">
    <h1>Chest Exercises</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Chest'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div> 
    <div class="well">
    <h1>Abdominal Exercises</h1>
    <%= collection_check_boxes(:exercise, :name, Exercise.where("muscle_group = 'Abs'"), :id, :name) do |b| %>
    <%= b.label(:"name" => b.value) { b.check_box + b.text } %><br>
    <% end %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

FitHub/app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

FitHub/app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>