FitHub/config/routes.rb
Rails.application.routes.draw do
  get 'create/destroy'

  resources :likes

  resources :friendships

  root 'pages#index'
  get 'users/profile'
  get 'users/home'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'users/show', to: 'users#profile'
  delete 'sign_out', to: 'sessions#destroy'
  resources :exercises
  resources :users
  resources :workouts
  resources :users_workouts
  resources :users_gyms
  resources :workouts_exercises
  resources :weekdays
  resources :weekdays_workouts
  get 'my_workouts', to: 'workouts#my_workouts'
  get 'followed', to: 'workouts#followed'
  post 'results', to: 'gyms#results'
  resources :gyms

end

FitHub/app/models/exercise.rb
class Exercise < ActiveRecord::Base
  # has_many :workout_exercises
  # has_many :workouts, through: :workout_exercises
  has_many :workouts_exercises
  has_many :workouts, through: :workouts_exercises
  has_many :sets_and_reps
end

FitHub/app/models/friendship.rb
class Friendship < ActiveRecord::Base
belongs_to :user
belongs_to :friend, :class_name => "User"
end

FitHub/app/models/gym.rb
class Gym < ActiveRecord::Base
  validates_uniqueness_of :address
  has_many :users_gyms
  has_many :users, through: :users_gyms

  def joined_gyms(user)
    UsersGym.where(:user_id => user.id, :gym_id => self.id).first
  end
end

FitHub/app/models/gyms_user.rb
class GymsUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/like.rb
class Like < ActiveRecord::Base
 belongs_to :user
 belongs_to :workout
end

FitHub/app/models/sets_and_rep.rb
class SetsAndRep < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_gyms
  has_many :gyms, through: :users_gyms
  has_many :users_workouts
  has_many :workouts, through: :users_workouts, :dependent => :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # has_many :likes
  # has_many :workouts, :through => :likes
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      # image: auth['info']['image']
    )
  end

  def is_friend?(friend_id)
    friendships.collect {|friendship| friendship.friend_id}.include?(friend_id)
  end
end

FitHub/app/models/users_gym.rb
class UsersGym < ActiveRecord::Base
  belongs_to :user
  belongs_to :gym
end

FitHub/app/models/users_workout.rb
class UsersWorkout < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout

   def self.notexist?(user, workout)
     !UsersWorkout.exists?(:user_id => user.id, :workout_id => workout.id)
   end
end

FitHub/app/models/weekday.rb
class Weekday < ActiveRecord::Base
  has_many :weekdays_workouts
  has_many :workouts, through: :weekdays_workouts
end

FitHub/app/models/weekdays_workout.rb
class WeekdaysWorkout < ActiveRecord::Base
  belongs_to :weekday
  belongs_to :workout
end

FitHub/app/models/workout.rb
class Workout < ActiveRecord::Base
 has_many :workouts_exercises
 has_many :exercises, through: :workouts_exercises
 has_many :users_workouts
 has_many :users, through: :users_workouts
 has_many :likes
 has_many :sets_and_reps
 has_many :weekdays_workouts
 has_many :weekdays, through: :weekdays_workouts
 attr_accessor :sets
 attr_accessor :reps
 attr_accessor :ex_num
 attr_accessor :days


 def followed_workouts(user)
   UsersWorkout.where(:user_id => user.id, :workout_id => self.id).first
 end

 def self.search(search)
   amt_for_category_search = where('category LIKE ?', "%#{search}%").count
   amt_for_name_search = where('name LIKE ?', "%#{search}%").count
   amt_for_creator_search = where('creator like ?', "%#{search}%").count

   if amt_for_category_search > amt_for_name_search && amt_for_category_search > amt_for_creator_search
     where('category LIKE ?', "%#{search}%")
   elsif amt_for_name_search > amt_for_creator_search && amt_for_name_search > amt_for_category_search
     where('name LIKE ?', "%#{search}%")
   else amt_for_creator_search > amt_for_name_search && amt_for_creator_search > amt_for_category_search
     where('creator like ?', "%#{search}%")
   end
 end

end

FitHub/app/models/workouts_exercise.rb
class WorkoutsExercise < ActiveRecord::Base
  belongs_to :workout
  belongs_to :exercise
end

FitHub/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_auth, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json

  def index
    @users = User.all - [current_user]
  end

  def home
    if current_user
      render 'home'
    else
      redirect_to root_url
    end
  end

  def show
    @workout = Workout.find_by_id(params[:id])
  end

  # GET /users/1
  # GET /users/1.json

  def profile
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to users_profile_path, notice: 'You Just Updated Your Profile!' }
        format.json { render :profile, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:c_bodyweight, :c_bench, :c_squat, :c_deadlift, :t_bodyweight, :t_bench, :t_squat, :t_deadlift)
    end

    def set_auth
      @auth = session[:omniauth] if session[:omniauth]
    end
end

FitHub/app/helpers/exercises_helper.rb
module ExercisesHelper
end

FitHub/app/helpers/gyms_helper.rb
module GymsHelper
end

FitHub/app/helpers/gyms_users_helper.rb
module GymsUsersHelper
end

FitHub/app/helpers/likes_helper.rb
module LikesHelper
end

FitHub/app/helpers/pages_helper.rb
module PagesHelper
end

FitHub/app/helpers/sessions_helper.rb
module SessionsHelper
end

FitHub/app/helpers/users_helper.rb
module UsersHelper

  def display_status(alert_type, flash_type)
    <<-eos
    <div class="container-fluid" id="medium_size">
      <div class="alert alert-#{alert_type}" role="alert">
        <p align="center">
          #{send(flash_type)}
        </p>
      </div>
    </div>
    eos
  end
end

FitHub/app/helpers/weekdays_helper.rb
module WeekdaysHelper
end

FitHub/app/helpers/workouts_helper.rb
module WorkoutsHelper
end

FitHub/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div align="center">
    <div class="well well-sm">
      <%= f.label "Current Body Weight" %>
      <%= f.text_field :c_bodyweight %><br>
      <%= f.label "Target Body Weight" %>
      <%= f.text_field :t_bodyweight %><br><br>

      <%= f.label "Current Bench Weight" %>
      <%= f.text_field :c_bench %><br>
      <%= f.label "Target Bench Weight" %>
      <%= f.text_field :t_bench %><br><br>

      <%= f.label "Current Squat Weight" %>
      <%= f.text_field :c_squat %><br>
      <%= f.label "Target Squat Weight" %>
      <%= f.text_field :t_squat %><br><br>

      <%= f.label "Currrent Deadlift Weight" %>
      <%= f.text_field :c_deadlift %><br>
      <%= f.label "Target Deadlift Weight" %>
      <%= f.text_field :t_deadlift %><br><br>
    </div>



    <div class="actions">
      <%= f.submit "Update Profile", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

FitHub/app/views/users/edit.html.erb
<div align="center">
  <h1>Editing Stats</h1><br>
</div>

<%= render 'form' %>
<div align="center">
  <h3><%= link_to 'Back', users_profile_path %></h3>
</div>

FitHub/app/views/users/home.html.erb
<% if current_user.workouts.empty? %>

<div align="center">
  <div class="container-fluid">
    <h1>Hey <%= current_user.name %>, Welcome to FitHub!</h1>
    <h3>Today is <%= Time.now.strftime("%B %e, %Y")%></h3><br>
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2>What Workout Will You Conquer?</h2>
          <h3>Start by creating your first workout!</h3><br>
          <%= link_to "Create A Workout", new_workout_path, class: "btn btn-outline btn-primary btn-lg btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

<% else %>
<div align="center">
  <div class="container-fluid">
    <h1>Hey
      <%= current_user.name %>, it's nice to have you back on FitHub!</h1><br>
    <div class="well well-sm">
      <h2>Today is
        <%= Time.now.strftime("%B %e, %Y")%></h2>
      <h2>What Workout Will You Conquer?</h2>
    </div>
    <div class="well well-sm">
      <h2>The Latest Addition to My Workouts</h2><br>
      <% @recent_workout = current_user.workouts.last %>
      <% creator_id = @recent_workout.user_id %>
      <% creator = User.find_by_id(creator_id).name %>
      <h4>Created By:
        <%= creator%></h4>
      <h4>Name Of The Workout:
        <%= @recent_workout.name %></h4>
      <h4>Category:
        <%= @recent_workout.category %></h4>
      <h4>Description:
        <%= @recent_workout.description %></h4>
      <h4>Workout Challenges:
        <%= @recent_workout.challenges %></h4>
      <h3><%= link_to "Check Out This Workout!", @recent_workout %></h3>
    </div>
    <div class="well well-sm">
      <h2>These are the gyms you have joined!</h2>
      <% current_user.gyms.each do |gym| %>
      <%= link_to(gym) do %>
      <h3><%= gym.name %></h3>
      <% end %>
      <h3><%= gym.address %></h3>
      <% end %>
      
    </div>
  </div>

  <% end %>

FitHub/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Everyone On FitHub</h1></center><br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
        <div class="container-fluid" id="medium_size">
          <div class="well well-sm">
            <center>
              <h4><%= user.name %></h4>
                <% if current_user.is_friend?(user.id) %>
                  <small>Added!</small>
                <% else %>
                  <small><%= link_to "Follow", friendships_path(:friend_id => user), class:"btn btn-primary ", :method => :post %></small>

                <% end %>
            </center>
          </div>
        </div>
      <% end %>
  </tbody>
</table>

<br>

FitHub/app/views/users/profile.html.erb
<% if notice %>
<%= display_status("success", "notice").html_safe %>
<% end %>

<% if alert %>
<%= display_status("danger", "alert").html_safe %>
<% end %>

<div style="margin-left:100px">

</div>
<div class="row">
  <div class="col-md-8" style="margin-left:40px">
    <div class="panel panel-default">
      <div class="panel-body">
        <div align="center">
          <h1><%= current_user.name %></h1><br>
          <h2><i class="fa fa-bar-chart" id="black-icon"></i> Your Personal Stats</h2>
          <h5>Current Body Weight:
            <%= current_user.c_bodyweight %>
            lbs<br></h5>
          <h5>Current Bench Weight:
            <%= current_user.c_bench %>
            lbs<br></h5>
          <h5>Current Squat Weight:
            <%= current_user.c_squat %>
            lbs<br></h5>
          <h5>Current Deadlift Weight:
            <%= current_user.c_deadlift %>
            lbs<br></h5>
        </div><br><br>
      </div>
      <div align="center">
        <h2>
          <i class="fa fa-child" id="black-icon"></i>
          Your Future Goals</h2>
        <h5>Target Body Weight:
          <%= current_user.t_bodyweight %>
          lbs<br></h5>
        <h5>Target Bench Weight:
          <%= current_user.t_bench %>
          lbs<br></h5>
        <h5>Target Squat Weight:
          <%= current_user.t_squat %>
          lbs<br></h5>
        <h5>Target Deadlift Weight:
          <%= current_user.t_deadlift %>
          lbs<br></h5><br>
        <div class="button">
          <h3><%= link_to '<i class="fa fa-edit fa-lg"></i> Edit Profile'.html_safe,  edit_user_path(current_user.id), class: "btn btn-primary" %></h3>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-primary" id= "friends_panel">
        <div class="panel-heading">Friends</div>
        <div class="panel-body">
          <% if current_user.friendships.count == 1 %>
          <i class="fa fa-user fa-lg">
            Following:
            <%= current_user.friendships.count %></i>
          <% else %>
          <i class="fa fa-user fa-lg">Following:
            <%= current_user.friendships.count %>
          </i>

          <% end %>
          <ul>
            <% for friendship in current_user.friendships %>

            <%= friendship.friend.name %>
            |
            <%= link_to "Remove", friendship, :method => :delete, class: "btn btn-primary btn-xs" %><br>

            <% end %>
          </ul>

          <p><%= link_to "Find Friends", users_path, class: "btn btn-primary btn-xs" %></p>
          <% if current_user.inverse_friends.count == 1 %>
          <i class="fa fa-users fa-2x">
            Followers:
            <%= current_user.inverse_friends.count %>
          </i>
          <% else %>
          <i class="fa fa-users fa-2x">
            Followers:
            <%= current_user.inverse_friends.count %>
          </i>
          <% end %>

          <ul>
            <% for user in current_user.inverse_friends %>
            <%= user.name %>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="panel panel-primary">
        <div class="panel-heading">Gyms you have joined!</div>
        <div class="panel-body">
          <ul>
            <% current_user.gyms.each do |gym| %>
            <%= link_to(gym) do %>
            <h4 style="color: #3c9ce7;"><%= gym.name %></h4>
            <% end %>
            <%= gym.address %><br>
            <% if gym.joined_gyms(current_user) %>
            <%= form_for gym.joined_gyms(current_user), method: :delete do |f| %>
            <h4><%= f.submit "Unfollow This Gym", class: "btn btn-primary btn-xs"%></h4>
            <% end %>
            <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

FitHub/app/views/users/show.html.erb
<% @user = User.find(params[:id])%>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">

    <div class="panel panel-default">
      <div class="panel-heading">
          <center><h1><%= @user.name %></h1></center>
      </div>
      <center>
        <h2>Most Recent Workout</h2>
        <%= link_to(@user.workouts.where(:user_id => @user.id).last) do %>
          <h3><%= @user.workouts.where(:user_id => @user.id).last.name %></h3>
        <% end %>
        <h2>Joined Gyms</h2>
        <% @user.gyms.each do |gym| %>
          <%= link_to(gym) do %>
            <h3><%= gym.name%></h3>
          <% end %>
          <h3><%= gym.address %></h3>
          <% end %>

      </center>


    </div>
  </div>
  <div class="col-md-3"></div>
</div>